### ISSUE TITLE
Activate Travis CI integration

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-deep-links#16]
hey Sean, can you go to https://travis-ci.org/profile/OneBusAway and activate Travis for this repo?

**Comment by aaronbrethorst** [comment]
cc @sayhiben

**Comment by barbeau** [comment]
Done!  Let me know if you have any issues.  I've set it to build only if `.travis.yml` is present - let me know if you want me to change that.
