### ISSUE TITLE
Add `start_date` and `end_date` to surveys 

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-deep-links#175]
From our conversation with Devin Braun. 

## User Story

as a transit agency employee,
I want to add explicit start and end dates to surveys,
so that I don't have uncheck the 'available' checkbox

## Acceptance Criteria

- [x] Add optional `start_date`and `end_date` datetime fields to the Survey model (i.e. create a new migration)
- [x] Add date time pickers to the survey form and make sure that those fields can be set from the `#create` and `#update` actions
- [x] Filter out surveys that are outside of the `start_date` and `end_date` ranges from the API's `#index` action.
- [x] Write specs that validate the model, the CRUD experience, and the API all work as expected.

**Comment by Ahmedhossamdev** [comment]
Also, should we remove the available column?

**Comment by Ahmedhossamdev** [comment]
Should both start_date and end_date be required? I know that they are optional fields, but what if a user enters only the start_date? Is that acceptable, or should both fields always be filled?
