### ISSUE TITLE
Fix trip status deep linking by hosting a map with relevant information on Obaco

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-deep-links#35]
OBA 2.0 in Puget Sound broke the format of deep links that the site is using. We need to create a page hosted on Obaco that shows the status of the specified trip.

See https://github.com/OneBusAway/onebusaway-android/issues/715#issuecomment-572250535 for more information about this feature, how to access it, and more.

The basic idea I have here is that the core experience shown at https://pugetsound.onebusaway.org/m/?q=1_19750 is essentially replicated on Obaco.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/2254/186535347-36e43099-a22e-4f99-9c9c-cb7af0aede85.png">

**Comment by bencodeorg** [comment]
@aaronbrethorst finally getting around to looking at this -- I'm all set up locally and starting to play around with things. 

I'm looking at the comment you linked above -- is the problem that there literally is no trip page any more on pugetsound.onebusaway.org? Or there is one, but you'd prefer to host the map on obaco so we have more control of what it looks like (eg, could implement a browser version of what [you described here](https://github.com/OneBusAway/onebusaway-ios/issues/449) for folks without the OBA app)?

**Comment by aaronbrethorst** [comment]
Hey @bencodeorg - apologies for the slow response. There _are_ trip pages, but the URL format is not guessable in a way that would be usable by the OBA iOS app. Additionally, the URL format in Puget Sound is very likely different from the URL format in other regions, which means we'd have to keep track of the URL format for trip pages on a region-by-region basis.

It would be much too difficult and error prone to try to manage this experience, and so I think the only tenable option is to host a map on the onebusaway.co website that can provide a trip experience to users.
