### ISSUE TITLE
[onebusaway] [obaco] Production NoMethodError: undefined method `web_url' for nil:NilClass

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-deep-links#8]
View full error details at:
https://api.heroku.com/myapps/app58523565@heroku.com/addons/airbrake:free-hrku?url=https%3A%2F%2Fherokuapp58523565herokucom.airbrake.io%2Fprojects%2F135959%2Fgroups%2F1866082199715019853%2Fnotices%2F1866082199372355717
Error type:
NoMethodError

Error message:
undefined method `web_url' for nil:NilClass

Where:
stops#trips
File:
[PROJECT_ROOT]/app/controllers/stops_controller.rb, line 24

URL:
http://www.onebusaway.co/regions/12/stops/wemapp_195/trips?trip_id=wemapp_42_17&service_date=1484694000000&stop_sequence=20
Backtrace summary:
[PROJECT_ROOT]/app/controllers/stops_controller.rb:24:in arrivals
[PROJECT_ROOT]/app/controllers/stops_controller.rb:28:in trips

**Comment by sayhiben** [comment]
Looks like it's due to calling `find_by` instead of `find_by!` in `StopsController#arrivals`.
