### ISSUE TITLE
Track historical arrival and departure times

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-deep-links#9]
Give users a sense of historical on-time departure/arrival rates by tracking arrival and departure times.

Check out the documentation for GTFS feeds vended by OBA: http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/gtfs-realtime.html

Specifically, look at `trip-updates-for-agency`. You can view a plain text version by going to this URL: http://api.pugetsound.onebusaway.org/api/gtfs_realtime/trip-updates-for-agency/1.pbtext?key=TEST

I bet we could track the tuple (agency, day of week, time of day, delay, and possibly the route ID) and develop an on-time prediction model based on that. The only big, open question for me is whether or not route IDs are relatively static or not. I don't know the answer offhand, but I'm sure that @barbeau would know the answer. It's a pity Levi doesn't have spare time, as this is totally in his wheelhouse. :)

Once we had, say, a week or so of data, I bet we could start building a meaningful prediction model. You'd plug in (agency, day of week, time of day, route ID) and get back the system's best guess on what your delay will be.

Giving users a better sense of whether the "5 minute delay" on their Seattle #8 is likely to be real or a complete lie (hint: lie. more like FOREVER.) will, I expect, give them more confidence in the transit system as a whole, and will also help to highlight problem areas where data is consistently wrong.

**Comment by aaronbrethorst** [comment]
@sayhiben update with more data

**Comment by barbeau** [comment]
Unfortunately `route_ids` aren't guaranteed to persist across GTFS updates.  This is included as one of the new GTFS Best Practices (http://gtfs.org/best-practices/#publishing_3), although it's going to take a while to see results in practice.  Currently RVTD region uses UUIDs apparently generated by Trapeze Streets which change every GTFS export.

IMHO, ideally these stats would be calculated by the backend as the source real-time data is fetched, as it would likely see more frequent updates to the data than a client to the OBA REST API.  However, obviously in our case there are limitations to deploying something quickly to all regions that's part of the backend.

So, as part of this, are you trying to figure out the ground-truth value of when the actual arrival/departure time was?  Or just calculate stats on the provided arrival/departure time, whether or not it's accurate?

**Comment by aaronbrethorst** [comment]
> Unfortunately route_ids aren't guaranteed to persist across GTFS updates

How frequent are GTFS updates?

> So, as part of this, are you trying to figure out the ground-truth value of when the actual arrival/departure time was? Or just calculate stats on the provided arrival/departure time, whether or not it's accurate?

I'd love to be able to offer a range of historical arrival/departure times, along with the median lateness over the past 7 or 30 days, or whatever, if that exists.

e.g.

```
Route 10: 7 minute delay
(Last 30 days average: departed 8 minutes late)
```

**Comment by barbeau** [comment]
>How frequent are GTFS updates?

Roughly four times a year, although some many push out updates more frequently to fix bugs, etc.

You might want to check out Transitland's Onestop ID - https://transit.land/documentation/onestop-id-scheme/.

This theoretically solves the problem of tracking IDs across GTFS updates.  They offer an API that should allow you to reconcile this (although I haven't taken a look at it yet), or you could code the algorithm yourself.

Have you considered producing averages for each route direction (e.g., Route 10 North vs. South)?  This gets significantly harder to track over updates, as `trip_ids` are almost guaranteed to change across updates (GTFS Best Practices don't require these to persist).

**Comment by aaronbrethorst** [comment]
Cool, thanks for the background, Sean. Sounds like we aren't in a position to implement this at this time, unfortunately.
